<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <NoWarn>$(NoWarn);MSB3277</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4022.49" />
    <PackageReference Include="System.Management" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Web\package.json" />
    <None Include="Web\vite.config.js" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\sun.png" />
    <EmbeddedResource Include="Resources\volume.png" />
  </ItemGroup>

  <Target Name="BuildWebFrontend" BeforeTargets="PrepareForBuild">
    <Exec WorkingDirectory="$(MSBuildProjectDirectory)\Web" Command="pnpm build" />
  </Target>

  <Target Name="CopyWebFrontendOutput" AfterTargets="BuildWebFrontend">
    <ItemGroup>
      <WebFrontendFiles Include="..\..\dist\web\**\*" />
    </ItemGroup>

    <Copy
      SourceFiles="@(WebFrontendFiles)"
      DestinationFiles="@(WebFrontendFiles->'$(OutputPath)Web\dist\%(RecursiveDir)%(Filename)%(Extension)')" />
  </Target>

</Project>
